Test Environment=dev
Base URL=https://awddev.trialclient1.awdcloud.co.uk/awdServer/awd/services/v1/user/businessareas
Username=JPANICKE
Execution Time=2025-11-25 17:14:24
Executed By=JohnPanicker
